### ISSUE TITLE
test issuelock 异常

### ISSUE THREAD

**Issue by cooljsz** [EosTokenMarket/tokenlock#3]
test方法中的
cleos push action tokenlock issuelock '["initc", "100.00 CVBT", 100, 2, "2018-08-06T5:21:0","mmmm"]' -p boss
执行时出现异常
Error 3050003: eosio_assert_message assertion failure

另:claim 方式是什么作用?

**Comment by vchengsong** [comment]
命令中的参数“2018-08-06T5:21:0”是发行时间，这个时间必须大于当前的时间，并且不能超过当前时间1个月，也就是设置为未来1个月之内的时间。
另外上面使用的时间是UTC时间，中国一般用+8 区时间，因此北京时间 -8 就是UTC时间。
